algoritmo "Atv.19 Ex1"
// Diciplina : Lógica de programação
// Autor : EduFM e Marcelinho
// Data : 14/04/2026
var
// Variaveis :3
   nota, freq, teste: Real

inicio
// Codiguinhos ^w^
   escreval ("Teste de aprovação do aluno de acordo com a frequência dele.")
   escreva ("Digite a nota do aluno: ")
   leia (nota)
   
   escreva ("Agora a frequência dele: ")
   leia (freq)

        limpatela
//If
   se (nota >= 7) e (freq >= 75) entao
    escreval ("Aprovado!")
   senao
        escreval ("Reprovado...")
   fimse

fimalgoritmo

