algoritmo "Atv.19 Ex3"
// Diciplina : Lógica de programação
// Autor : EduFM e Marcelo
// Data : 14/04/2026
// Seção de Declarações 
var
// variaveis :3
   s: caracter

inicio
// Codiguinhos ^w^
   escreval ("Seu produto está em esgotado?")
   escreval ("Digite s ou n:")
   leia (s)

// os ifs
   se nao (s = "s") entao
      escreva ("Então venda os produtos do estoque")
   senao
        escreva ("Reponha")
   fimse

fimalgoritmo
