algoritmo "Aula19 ex2"
// Diciplina: Lógica de programação
// Autor : Marcelo Barbosa e EduFM
// Data : 14/04/2026
var
//variante

          idade: real

inicio
//Comandos


          escreval ("Verificação de idade para entrada gratuita!")
          
          escreval ("Informe a dua idade aqui: ")
          leia (idade)
          
          //se
          
          se (idade <= 5) ou (idade >= 65) entao
          escreval ("você tem acesso a entrada gratuita")
          senao
          escreval ("você não tem acesso a entrada gratuita")
          fimse




fimalgoritmo
